### ISSUE TITLE
Unable to install in 1.34.0

### ISSUE THREAD

**Issue by vicky002** [PeterHdd/github-folder#1]
Hi, 

I tried installing extension on latest VS code and it gives me this error. 

Can you please specify which version extension supports? 

<img width="473" alt="Screenshot 2019-06-10 at 8 35 32 AM" src="https://user-images.githubusercontent.com/5517129/59170122-d2b67080-8b5a-11e9-8a7f-57fc1c2afe95.png">

**Comment by PeterHdd** [comment]
Hello,

I have updated it to be compatible with vscode versions 1.33.0+.
